### ISSUE TITLE
Firebase Deploy Errors

### ISSUE THREAD

**Issue by wonexo** [kelvinkamau/Vibranium#3]
Here are the Result

```i  hosting[dscyabatech]: beginning deploy...            │
i  hosting[dscyabatech]: found 0 files in public        │
✔  hosting[dscyabatech]: file upload complete           │                                                                                 "Jedi" 22:35 13-Sep-18
i  database: releasing rules...                         │
✔  database: rules for database dscyabatech released suc│
cessfully                                               │
✔  storage: released rules storage.rules to firebase.sto│
rage/dscyabatech.appspot.com                            │
i  hosting[dscyabatech]: finalizing version...          │
                                                        │
Error: HTTP Error: 404, Not Found```

**Comment by kelvinkamau** [comment]
## 1. Getting started
* Start by adding all the folders and files inside a folder called ```public```
* Create a project on [firebase](https://console.firebase.google.com/)

## 2. Deploying to firebase hosting
* Install the Firebase CLI
Run ```npm install -g firebase-tools```
* Connect your local machine to your Firebase account
Run ```firebase login```
* Initialize your site
Run ``` firebase init```
* Deploy your site
``` firebase deploy```

**Comment by kelvinkamau** [comment]
# Initializing
<img src="https://github.com/kelvinkamau/Vibranium/blob/master/images/firebase.PNG"/>

# Deploying
<img src="https://github.com/kelvinkamau/Vibranium/blob/master/images/firebase2.PNG"/>
