### ISSUE TITLE
fix : Serve images that are appropriately-sized to save cellular data and improve load time

### ISSUE THREAD

**Issue by kelvinkamau** [kelvinkamau/Vibranium#59]

**Comment by kelvinkamau** [comment]
![fada](https://user-images.githubusercontent.com/20049411/52236231-51fb1580-28d7-11e9-8d9d-348b8dd836c7.PNG)

**Comment by ashinzekene** [comment]
http://squoosh.app

Very good for compressing and resizing photos. We should have at least two versions of the images of different sizes

**Comment by kelvinkamau** [comment]
Fantastic....on it right away!

**Comment by stellakaniaru** [comment]
Hey @ashinzekene mind helping us get this done?
