### ISSUE TITLE
add page pre-loader similar to the one on github/medium

### ISSUE THREAD

**Issue by anniemburu** [kelvinkamau/Vibranium#63]

**Comment by OlenaVyshnevska** [comment]
Hi, can I work on this?

**Comment by stellakaniaru** [comment]
Hey @OlenaVyshnevska you definitely can.

The pre-loader should be similar to the one on Github/Medium pages.
![pre-loader](https://user-images.githubusercontent.com/18654569/56462708-5b712580-63d0-11e9-8c65-d7a75adea2d5.jpeg)
