### ISSUE TITLE
Reorder items

### ISSUE THREAD

**Issue by kelvinkamau** [kelvinkamau/Vibranium#67]
Preferred arrangement of divs on a mobile device....```image, description, button``` for mobile devices only.

![localhost_63342_vibranium2019_index html__ijt ke1egf3lp1297368iffc971tq9 iphone 6_7_8](https://user-images.githubusercontent.com/20049411/52432899-c4106c00-2b1c-11e9-8fca-943801ba5543.png)

**Comment by kelvinkamau** [comment]
@stellakaniaru whatever changes you made also interfered with other images which shouldn't be affected. They include ```android.png``` & ```cloud.png```
![whatsapp image 2019-02-11 at 14 55 52](https://user-images.githubusercontent.com/20049411/52561745-59597c00-2e0d-11e9-9089-486546bf0b1b.jpeg)

**Comment by stellakaniaru** [comment]
resolved
