### ISSUE TITLE
Accidental Push to master

### ISSUE THREAD

**Issue by lewis-munyi** [kelvinkamau/Vibranium#77]
1.  I accidentally pushed some changes to master. Oops!
2.  Fixed fonts on the whole site. Used legible material fonts consistently throughout the app.
3.  Used a consistent accent color for the whole app.
4.  Tried fixing @stellakaniaru 's team cards. It works well on chrome but I've just discovered it doesn't work well on firefox.

**This should've been a pull request but oh well.**

**Comment by kelvinkamau** [comment]
Don't you think this looks a bit awkward?

![image](https://user-images.githubusercontent.com/20049411/52550612-da068100-2de9-11e9-90c4-7a634559ec2b.png)

## compare

![image](https://user-images.githubusercontent.com/20049411/52550662-0ae6b600-2dea-11e9-90ff-438d8bddd38a.png)

I have reverted some changes you made. Kindly use a PR to make changes. I would like to test across different devices and browsers as well to make sure it doesnt break.

**Comment by ashinzekene** [comment]
@kelvinkamau You can go to settings/branches to prevent accidental pushes to master

**Comment by kelvinkamau** [comment]
Thanks @ashinzekene I already did. 👍
