### ISSUE TITLE
Proposed project card design for project.html page

### ISSUE THREAD

**Issue by kelvinkamau** [kelvinkamau/Vibranium#85]
![projectcard](https://user-images.githubusercontent.com/20049411/52999123-077cab80-3436-11e9-96d7-56b9266b946b.PNG)

**Comment by kelvinkamau** [comment]
![projectcard2](https://user-images.githubusercontent.com/20049411/53080092-f2248180-3508-11e9-9765-320f685ec0a5.png)

**Comment by stellakaniaru** [comment]
On it
