### ISSUE TITLE
Upgrade to bootstrap v4.3.1

### ISSUE THREAD

**Issue by kelvinkamau** [kelvinkamau/Vibranium#87]
@stellakaniaru help us migrate to [v4.3.1](https://github.com/twbs/bootstrap/releases/tag/v4.3.1)

**Comment by stellakaniaru** [comment]
Working on it :)

**Comment by stellakaniaru** [comment]
@TNkemdilim mind taking this one up?

**Comment by TNkemdilim** [comment]
Just seeing this now. Sure, I'll treat asap.
