### ISSUE TITLE
Add 404 error page

### ISSUE THREAD

**Issue by kelvinkamau** [kelvinkamau/Vibranium#94]

**Comment by pbrahmbhatt3** [comment]
can I work on this? Can you provide some more information please

**Comment by kelvinkamau** [comment]
Hi @pbrahmbhatt3
We just need an error page for when a user visits a wrong url on the website or clicks a link that directs to nowhere really. Just a basic 404 error page.

## Note : 
1. Should have a link to redirect to home
2. Excellent UI that matches our template theme

**Comment by AbdullahiAbdulkabir** [comment]
Can this issue be closed, so we can know which issues we can work on
